### ISSUE TITLE
preprocessing notebook, directory structure, and metadata

### ISSUE THREAD

**Issue by jpgard** [KinWaiCheuk/ReconVAT#1]
Hi, thanks for sharing this repo and pretrained models. 

However, it's difficult to make use of the repo without either the preprocessing notebook `Preprocessing.ipynb`, or a description of how the downsampled audio files and associated metadata should be stored.

Could you include that notebook in the repo, or alternatively, describe how we can extract the relevant info from MIDI to TSV, and where to place the downsampled audio files in order to make use of the model?

Thanks!

**Comment by KinWaiCheuk** [comment]
Hi jpgard, thanks for using my repo, and sorry for the dirty code. I didn't realize that `Preprocessing.ipynb` was missing from this repo until you pointed it out. I have uploaded it. Please feel free to let me know if you have further questions.

Meanwhile, I am in the process of cleaning up the code further to make it easier to use. But I spent unexpectedly long time working on the auto download and auto preprocessing package.
https://github.com/KinWaiCheuk/AudioLoader

Now this package is nearly ready, I am trying to make it compatible with this repo.

**Comment by jpgard** [comment]
Thanks @KinWaiCheuk ! I am mostly interested in MusicNet for a current project, and was able to get the data preprocessed using the .ipynb you uploaded.

We are hoping to run inference using the pretrained model weights on MusicNet, to get the predicted MIDI for each track. However, the README references a file `evaluate.py` which also does not appear to be in the repo.

It seems like what I should really be using for this, though, is maybe `transcribe_files.py`? Can you give a usage example of how to run `transcribe_files.py`, including where the data should be located and any specific about directory structure and naming? I have MIDI, FLAC, and TSVs for MusicNet all in separate subdirectories but can rearrange as needed...

Thanks again.

**Comment by KinWaiCheuk** [comment]
For you case where you just need to get the predicted MIDI files, `transcribe_files.py` is enough to get the job done. 

`evaluate.py ` is for calculating different metrics such as framewise F1 scores, note-wise F1 scores. I have uploaded this file just now.

Just a side note, in this paper, I mainly explored the case when we have limited labels. In this case ReconVAT works better than other baseline models. All my pretrained weights are trained on limited labelled data as described in the paper.
So if you are aiming at getting a high transcription accuracy, you might want to train the model with more labelled and unlabelled data.

**Comment by jpgard** [comment]
Hm...when I try to run `transcribe.py` on just a single track, it OOMs even in a normal colab GPU instance.

Tried running it on CPU instead (changing the device in `transcribe_files.py`), but this led to the stack trace below.

Any suggestions, on either how to improve the memory usage, or to get it working with CPU? I am surprised that even a single inference cannot run on GPU with ~10GB RAM.

```
WARNING - transcription - No observers have been added to this run
INFO - transcription - Running command 'main'
INFO - transcription - Started
Loading files: 100% 1/1 [00:00<00:00,  5.33it/s]
STFT kernels created, time used = 0.4823 seconds
STFT filter created, time used = 0.0085 seconds
Mel filter created, time used = 0.0085 seconds
Loading model weight
ERROR - transcription - Failed after 0:00:01!
Traceback (most recent calls WITHOUT Sacred internals):
  File "transcribe_files_cpu.py", line 71, in main
    model.load_state_dict(torch.load(weight_path, map_location=device))
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 584, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 842, in _load
    result = unpickler.load()
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 834, in persistent_load
    load_tensor(data_type, size, key, _maybe_decode_ascii(location))
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 823, in load_tensor
    loaded_storages[key] = restore_location(storage, location)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 800, in restore_location
    return default_restore_location(storage, map_location)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 179, in default_restore_location
    + location + ")")
RuntimeError: don't know how to restore data location of torch.FloatStorage (tagged with cpu:0)
```

**Comment by KinWaiCheuk** [comment]
When loading the model weights using cpu, did you use `device='cpu'`? The error message shows that you are trying to use `device='cpu:0'`. Can you try `device='cpu'` instead?

As for the GPU memory usage, are you transcribing a full track (3-4 minutes long)? Since this model uses several self-attention layers, the GPU memory usage increases as the input length increases. During my training, I was using 20s as my clip length.

**Comment by jpgard** [comment]
Thanks for the quick replies.

Yes, we need the full-track transcriptions for MusicNet tracks, so we are running on the full wav files.

Unfortunately, it still OOMs when using `device='cpu'` as well.

How did you obtain inference/eval results on the full musicnet tracks without ever running on a full audio file? Are there utilities anywhere to stitch together 20s chunks of MIDI into a full track?

**Comment by KinWaiCheuk** [comment]
Hi jpgard, I ran the script just now and confirm that it takes around 50GB RAM to infer a full length track. Since in our lab, we have access to a workstation with 256GB RAM, so we didn't even notice this problem...

One workaround is that we split the full waveform/spectrogram into 20s chunks, and get 20s chunks of pianorolls.
Then we append these 20s pianorolls back to the full pianoroll before the [for loop](https://github.com/KinWaiCheuk/ReconVAT/blob/56c3aee54d3688a3d6e875a53bed2220d2e69013/transcribe_files.py#L19).

Hopefully it can avoid the memory explosion problem caused by the self-attention layers.

**Comment by jpgard** [comment]
Just wanted to say, thank you for the follow-up info. This was really helpful. Ended up rolling my own pipeline to chunk and downsample the inputs, but we were able to get inference running on GPU with the small inputs. :)

If I have time, I will submit a PR with some more detailed instructions for folks (like me) trying to do inference with the model, in an ipynb; maybe that will be helpful.
