### ISSUE TITLE
Weights are unavailable 

### ISSUE THREAD

**Issue by amwojtowicz** [KinWaiCheuk/ReconVAT#7]
Hello everybody, 
I found that the link provided in the README is no longer active. Would it be possible to update it?

**Comment by KinWaiCheuk** [comment]
I am so sorry for the late reply. I overlooked this issue.
I have updated the download, and for your convenience, let me also provide the link here.
https://sutdapac-my.sharepoint.com/:f:/g/personal/kinwai_cheuk_alumni_sutd_edu_sg/EiWLNCgEbFNFnaGn4liCEOwBxOvOW8CnOi3hoeYiXrXxzQ?e=6m1Mlf

Feel free to reopen this issue or create a new one if you face any problem.
